spring.datasource.url=jdbc:mysql://localhost:3306/examsystem
spring.datasource.username=root
spring.datasource.password=Abinaya@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect